### ISSUE TITLE
Scraper needs updated for new Term

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician-scrapers/serbia_national_assembly_members#3]
It's now mixing all the new people in with the old ones. Would be best if it scraped each of the historic terms individually (there are separate 'Current Legislature' and 'Legislature Archive' sections in the sidebar) with a 'term' column set.

**Comment by struan** [comment]
Fixed in 4aacc7706160797d627ee64a19af96769f4dd3ff
